networks:
  pelias_spain_mini:
    driver: bridge
services:
  libpostal:
    image: pelias/libpostal-service
    container_name: spain_mini_libpostal
    user: "${DOCKER_USER}"
    restart: always
    ports: [ "127.0.0.1:28400:4400" ]
    networks: [ "pelias_spain_mini" ]
  schema:
    image: pelias/schema:master
    container_name: spain_mini_schema
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
    networks: [ "pelias_spain_mini" ]
  api:
    image: tiskel/pelias-api:v1.0.4
    container_name: spain_mini_api
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=4000" ]
    ports: [ "0.0.0.0:28000:4000" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
    networks: [ "pelias_spain_mini" ]
  openstreetmap:
    image: tiskel/openstreetmap:v2.9.0
    container_name: spain_mini_openstreetmap
    user: "${DOCKER_USER}"
    environment:
      NODE_OPTIONS: "--max-old-space-size=16384"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_spain_mini" ]
  elasticsearch:
    image: pelias/elasticsearch:7.17.27
    container_name: spain_mini_elasticsearch
    user: "${DOCKER_USER}"
    restart: always
    ports: [ "127.0.0.1:28200:9200", "127.0.0.1:28300:9300" ]
    volumes:
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - "${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: [ "IPC_LOCK" ]
    security_opt:
      - seccomp=unconfined
    networks: [ "pelias_spain_mini" ]
