networks:
  pelias_dolnoslaskie:
    driver: bridge
services:
  libpostal:
    image: pelias/libpostal-service
    container_name: dolnoslaskie_libpostal
    user: "${DOCKER_USER}"
    restart: always
    ports: [ "127.0.0.1:4400:4400" ]
    networks: [ "pelias_dolnoslaskie" ]
  schema:
    image: pelias/schema:master
    container_name: dolnoslaskie_schema
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
    networks: [ "pelias_dolnoslaskie" ]
  api:
    image: tiskel/pelias-api:v1.0.2
    container_name: dolnoslaskie_api
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=4000" ]
    ports: [ "0.0.0.0:4000:4000" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
    networks: [ "pelias_dolnoslaskie" ]
  placeholder:
    image: pelias/placeholder:master
    container_name: dolnoslaskie_placeholder
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=4100" ]
    ports: [ "127.0.0.1:4100:4100" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
      - "./blacklist/:/data/blacklist"
    networks: [ "pelias_dolnoslaskie" ]
  whosonfirst:
    image: pelias/whosonfirst:master
    container_name: dolnoslaskie_whosonfirst
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_dolnoslaskie" ]
  openstreetmap:
    image: tiskel/openstreetmap:v1.8.6
    container_name: dolnoslaskie_openstreetmap
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_dolnoslaskie" ]
  openaddresses:
    image: pelias/openaddresses:master
    container_name: dolnoslaskie_openaddresses
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_dolnoslaskie" ]
  csv-importer:
    image: pelias/csv-importer:master
    container_name: dolnoslaskie_csv_importer
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
      - "./blacklist/:/data/blacklist"
    networks: [ "pelias_dolnoslaskie" ]
  transit:
    image: pelias/transit:master
    container_name: dolnoslaskie_transit
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_dolnoslaskie" ]
  polylines:
    image: pelias/polylines:master
    container_name: dolnoslaskie_polylines
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_dolnoslaskie" ]
  interpolation:
    image: pelias/interpolation:master
    container_name: dolnoslaskie_interpolation
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=4300" ]
    ports: [ "127.0.0.1:4300:4300" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_dolnoslaskie" ]
  pip:
    image: pelias/pip-service:master
    container_name: dolnoslaskie_pip
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=4200" ]
    ports: [ "127.0.0.1:4200:4200" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_dolnoslaskie" ]
  elasticsearch:
    image: pelias/elasticsearch:7.17.27
    container_name: dolnoslaskie_elasticsearch
    user: "${DOCKER_USER}"
    restart: always
    ports: [ "127.0.0.1:9200:9200", "127.0.0.1:9300:9300" ]
    volumes:
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - "${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: [ "IPC_LOCK" ]
    security_opt:
      - seccomp=unconfined
    networks: [ "pelias_dolnoslaskie" ]
  fuzzy-tester:
    image: pelias/fuzzy-tester:master
    container_name: dolnoslaskie_fuzzy_tester
    user: "${DOCKER_USER}"
    restart: "no"
    command: "--help"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "./test_cases:/code/pelias/fuzzy-tester/test_cases"
    networks: [ "pelias_dolnoslaskie" ]

