networks:
  pelias_uk:
    driver: bridge
services:
  libpostal:
    image: pelias/libpostal-service
    container_name: uk_libpostal
    user: "${DOCKER_USER}"
    restart: always
    ports: [ "127.0.0.1:5400:4400" ]
    networks: [ "pelias_uk" ]
  schema:
    image: pelias/schema:master
    container_name: uk_schema
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
    networks: [ "pelias_uk" ]
  api:
    image: pelias/api:master
    container_name: uk_api
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=4000" ]
    ports: [ "0.0.0.0:5000:4000" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
    networks: [ "pelias_uk" ]
  placeholder:
    image: pelias/placeholder:master
    container_name: uk_placeholder
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=4100" ]
    ports: [ "127.0.0.1:5100:4100" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_uk" ]
  whosonfirst:
    image: pelias/whosonfirst:master
    container_name: uk_whosonfirst
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_uk" ]
  openstreetmap:
    image: tiskel/openstreetmap:v1.2
    container_name: uk_openstreetmap
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_uk" ]
  openaddresses:
    image: pelias/openaddresses:master
    container_name: uk_openaddresses
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_uk" ]
  csv-importer:
    image: pelias/csv-importer:master
    container_name: uk_csv_importer
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_uk" ]
  polylines:
    image: pelias/polylines:master
    container_name: uk_polylines
    user: "${DOCKER_USER}"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_uk" ]
  interpolation:
    image: pelias/interpolation:master
    container_name: uk_interpolation
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=4300" ]
    ports: [ "127.0.0.1:5300:4300" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_uk" ]
  pip:
    image: pelias/pip-service:master
    container_name: uk_pip
    user: "${DOCKER_USER}"
    restart: always
    environment: [ "PORT=4200" ]
    ports: [ "127.0.0.1:5200:4200" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
    networks: [ "pelias_uk" ]
  elasticsearch:
    image: pelias/elasticsearch:7.17.27
    container_name: uk_elasticsearch
    user: "${DOCKER_USER}"
    restart: always
    ports: [ "127.0.0.1:9201:9200", "127.0.0.1:9301:9300" ]
    volumes:
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - "${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: [ "IPC_LOCK" ]
    security_opt:
      - seccomp=unconfined
    networks: [ "pelias_uk" ]
  fuzzy-tester:
    image: pelias/fuzzy-tester:master
    container_name: uk_fuzzy_tester
    user: "${DOCKER_USER}"
    restart: "no"
    command: "--help"
    volumes:
      - "./pelias.json:/code/pelias.json"
    networks: [ "pelias_uk" ]
